name: Run Kafka Producer

on:
  schedule:
    - cron: "*/5 * * * *"  # toutes les 5 minutes
  workflow_dispatch: # lancement manuel

jobs:
  run-producer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create confluent config from secrets
        run: |
          mkdir -p config
          cat > config/confluent_config.json <<EOL
          {
            "bootstrap.servers": "${{ secrets.BOOTSTRAP_SERVERS }}",
            "security.protocol": "SASL_SSL",
            "sasl.mechanism": "PLAIN",
            "sasl.username": "${{ secrets.SASL_USERNAME }}",
            "sasl.password": "${{ secrets.SASL_PASSWORD }}",
            "schema.registry.url": "${{ secrets.SCHEMA_REGISTRY_URL }}",
            "basic.auth.user.info": "${{ secrets.SCHEMA_REGISTRY_AUTH }}",
            "topic": "${{ secrets.TOPIC }}"
          }
          EOL

      - name: Run Kafka Producer
        run: python src/producer.py
